version: "3.9"

name: client_data_service
services:
  client_data_app:
    build: .
    container_name: client_data_app
    entrypoint: >
      sh -c "gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind unix:/tmp/fastapiapp.sock src.entrypoint:app"
    expose:
      - "8000"
    volumes:
      - socket_app:/tmp
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - socket_app:/tmp

  redis:
    image: redis:7.2.4
    container_name: redis
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 3s
      retries: 3

volumes:
  socket_app: